
language: ruby

rvm:
  #- 1.8.7 # no, since it doesn't get fun(a, *b, c) or fun0\n.fun1
  #- 1.9.3 # Travis broken September 2017
  #- 2.4.2
  - 2.5.8
  - 2.6.6
  - 2.7.2
  - jruby-9.2.14.0

#matrix:
#  include:
#    - rvm: jruby-9.1.13.0
#    #- env: JRUBY_OPTS="--profile.api"

#before_install: gem install bundler
script: bundle exec rspec
branches:
  only:
    - master
  #except:
  #  - master

cache: bundler

#env:
#  - FLOR_DEFAULT_TIMEOUT=7

